CMakeLists.txt

Hi Oliver,
Please review the changes.
Thanks and best regards,
Victor

Fix find psql libs

---

src/modules/ipfix/database/IpfixDbWriterSQL.cpp

Hi Oliver,
Please review the change of the loop condition we discussed last week.
Thanks and best regards,
Victor

Change loop condition.

---

src/modules/ipfix/database/IpfixDbWriterSQL.cpp

Hi Oliver,
This PR is only for the comment on flowstart's time unit.
BR,
Victor

Specify time unit for value in flowstart

---

src/modules/ipfix/database/IpfixDbWriterSQL.cpp

if (parsedData == 0) into if (*parsedData == 0)
Since parsedData is declared as char **parsedData = &values[colNum]
the condition "parsedData == 0" will always be evaluated as False
since parsedData contains the address of the array named "values"
without considering whether values[0] is 0 or not.

Change parsedData condition:

---

src/modules/ipfix/database/IpfixDbWriterSQL.cpp

Move decimal point according to factor and remove decimal part in string. Free memory before strdup.

Fix lexical cast exception

---

src/modules/ipfix/database/IpfixDbWriterMongo.cpp
src/modules/ipfix/database/IpfixFlowInspectorExporter.cpp

IPFIX_TYPEID_mplsLabelStackEntry1 was renamed to IPFIX_TYPEID_mplsTopLabelStackSection.
This fixed issue #23.

Fixed issue 23

---

src/common/TimeoutSemaphore.h
src/core/Source.h
src/modules/ipfix/IpfixSender.cpp

See commit messages for details on the bugs.
The log get very very spammy which should not happen at INFO level,  so these per-packet messages are downgraded to DEBUG.

Lower some ipfixsender messages to debug and 3 small bug fixes

---

src/modules/ipfix/Connection.cpp
src/modules/ipfix/Connection.h
src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
src/modules/ipfix/aggregator/AggregatorBaseCfg.h
src/modules/ipfix/aggregator/BaseAggregator.cpp
src/modules/ipfix/aggregator/BaseAggregator.h
src/modules/ipfix/aggregator/BaseHashtable.cpp
src/modules/ipfix/aggregator/BaseHashtable.h
src/modules/ipfix/aggregator/FlowHashtable.cpp
src/modules/ipfix/aggregator/FlowHashtable.h
src/modules/ipfix/aggregator/HashtableBuckets.h
src/modules/ipfix/aggregator/IpfixAggregator.cpp
src/modules/ipfix/aggregator/IpfixAggregator.hpp
src/modules/ipfix/aggregator/IpfixAggregatorCfg.cpp
src/modules/ipfix/aggregator/PacketAggregator.cpp
src/modules/ipfix/aggregator/PacketAggregator.h
src/modules/ipfix/aggregator/PacketAggregatorCfg.cpp
src/modules/ipfix/aggregator/PacketHashtable.cpp
src/modules/ipfix/aggregator/PacketHashtable.h

See commit messages for more details about the changes.

Allow active/inactive timer to be set to 0 and compare timer with wall clock

---

src/core/XMLDocument.cpp
src/modules/ipfix/CollectorCfg.h
src/modules/ipfix/IpfixCollectorCfg.cpp
src/modules/ipfix/IpfixExporterCfg.cpp
src/modules/ipfix/IpfixReceiverDtlsSctpIpV4.cpp
src/modules/ipfix/IpfixReceiverDtlsSctpIpV4.hpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.cpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.hpp
src/modules/ipfix/IpfixReceiverSctpIpV4.cpp
src/modules/ipfix/IpfixReceiverSctpIpV4.hpp
src/modules/ipfix/IpfixReceiverTcpIpV4.cpp
src/modules/ipfix/IpfixReceiverTcpIpV4.hpp
src/modules/ipfix/IpfixReceiverUdpIpV4.cpp
src/modules/ipfix/IpfixReceiverUdpIpV4.hpp
src/modules/ipfix/IpfixReceiverZmq.cpp
src/modules/ipfix/IpfixReceiverZmq.hpp
src/modules/packet/PSAMPExporterCfg.cpp

Use XML ID as Sensors module id in receivers

---

src/modules/packet/Template.cpp
src/modules/packet/Template.h

Added checks against MAX_TEMPLATE_FIELDS when adding template fields.
Added check against the current number of fields when getting a field's info.
Throw exceptions in case any of the checks fail.

Template field indexes not checked

---

.travis.yml

Demo of it working: https://travis-ci.org/nickbroon/vermont/builds/300229192
Probably worth creating a Travis account, so that you can have build status appear on PRs, etc

add Github Travis CI build

---

src/core/Graph.cpp
src/core/SensorManager.cpp
src/modules/analysis/RBSWormDetector.cpp
src/modules/ipfix/IpfixCsExporter.cpp
src/modules/ipfix/IpfixCsExporter.hpp
src/modules/ipfix/IpfixNetflowExporter.cpp
src/modules/ipfix/IpfixParser.cpp
src/modules/ipfix/IpfixPayloadWriter.cpp
src/modules/ipfix/IpfixReceiverFile.cpp
src/modules/ipfix/IpfixRecord.cpp
src/modules/ipfix/IpfixRecord.hpp
src/modules/ipfix/IpfixSampler.cpp
src/modules/ipfix/NetflowV9Converter.cpp
src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
src/modules/ipfix/aggregator/BaseAggregator.cpp
src/modules/packet/Observer.cpp
src/modules/packet/filter/SystematicSampler.h
src/tests/vermonttest/PrinterModule.cpp

Silence a whole bunch more compiler warnings.
Getting closer to being able to enable -Werror in CMakeList.txt

Minor static analysis warnings

---

src/common/openssl/OpenSSL.cpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.cpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.hpp

fixed remaining clang warnings for DTLS ON

fixed clang warnings for DTLS ON

---

src/modules/ipfix/IpfixParser.cpp
src/modules/ipfix/IpfixPrinter.cpp
src/osdep/linux/sysinfo.cpp
src/tests/vermonttest/TestSuiteBase.h

Solved the remaining clang warnings

solved the additional clang warnings

---

src/common/defs.h
src/common/openssl/SSLCTXWrapper.cpp
src/modules/analysis/autofocus_report.cpp
src/modules/analysis/fpsigmatcher/Utils.c
src/modules/analysis/fpsigmatcher/uthash.h
src/modules/ipfix/IpfixPrinter.cpp
src/modules/ipfix/IpfixPrinter.hpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.cpp
src/modules/ipfix/IpfixSender.cpp
src/modules/ipfix/aggregator/FlowHashtable.cpp
src/osdep/linux/ThreadCPUInterface.cpp

Fixed GCC warnings, both with DTLS_SUPPORT=ON and OFF

Fix gcc warnings

---

src/common/ipfixlolib/encoding.c
src/common/ipfixlolib/encoding.h
src/modules/ipfix/IpfixPrinter.cpp

added support for BE in IpfixPrinter

---

src/core/Cfg.cpp
src/modules/analysis/fpsigmatcher/KTree.c
src/modules/analysis/fpsigmatcher/Matcher.c
src/modules/analysis/fpsigmatcher/Signature.c
src/modules/analysis/fpsigmatcher/Utils.c
src/modules/ipfix/IpfixReceiverFile.cpp
src/modules/ipfix/IpfixRecord.cpp
src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
src/modules/ipfix/aggregator/FlowHashtable.cpp
src/modules/packet/PCAPExporterPipe.cpp
src/modules/packet/PSAMPExporterModule.cpp
src/modules/packet/filter/RandomSampler.cpp

Solved the scan-build detected bugs that were not considered false positives -- mainly caused by scan-build ignoring THROWEXCEPTION.

Solve scan build bugs

---

.travis.yml

updated the clang and the gcc versions used by travis

Update travis compiler versions

---

src/common/bloom/BloomFilterBase.h
src/common/defs.h
src/modules/analysis/fpsigmatcher/uthash.h
src/modules/idmef/PacketIDMEFReporter.cpp
src/modules/ipfix/IpfixPrinter.cpp
src/modules/ipfix/IpfixPrinter.hpp
src/modules/ipfix/aggregator/PacketHashtable.cpp
src/modules/packet/filter/HostFilter.cpp

Fixed warnings for older compiler versions.

Prepare code for werror

---

.travis.yml
CMakeLists.txt
src/common/ipfixlolib/ipfixlolib.c
src/common/ipfixlolib/ipfixlolib_dtls.c

Use make -k so that all warnings are ouput if there are any.
This is the future :-)

Use -Werror to fail the build on compiler warnings

---

src/common/Thread.h
src/common/ipfixlolib/ipfixlolib.c
src/modules/analysis/fpsigmatcher/Signature.c
src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
src/tests/vermonttest/AggregationPerfTest.cpp

Added checks to prevent out-of-bounds writings and unwanted memcpy ranges.

Solve potential buffer overflow bugs

---

.travis.yml
src/common/ConcurrentQueue.h
src/common/TimeoutSemaphore.h
src/common/msg.h
src/core/InstanceManager.h
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.cpp
src/modules/ipfix/IpfixReceiverDtlsUdpIpV4.hpp
src/modules/ipfix/TemplateBuffer.cpp
src/modules/ipfix/aggregator/IpfixAggregator.cpp
src/modules/ipfix/aggregator/PacketAggregator.cpp
src/modules/ipfix/aggregator/PacketHashtable.cpp
src/modules/packet/Observer.cpp
src/modules/packet/Packet.h
src/modules/packet/Template.h
src/modules/packet/filter/FilterModule.cpp

Fixes #105 by fixing all the printf specifiers in the debug code. Also adds Travis jobs to catch this in the future. (Note that this builds on #104, as they both touch the same debug code lines.)

Debug code build

---

src/common/ConcurrentQueue.h
src/common/TimeoutSemaphore.h
src/core/ConnectionQueue.h
src/modules/ipfix/aggregator/BaseAggregator.cpp

Debug logs are now useful, without hundreds/thousands of poll loop reports. (actual pops/pushes are still reported)
Couple of minor tidy/refactors a well.

Cleaner logging

---

src/modules/ipfix/database/IpfixDbReaderMySQL.cpp
src/modules/ipfix/database/IpfixDbWriterSQL.cpp

fix sql module

---

src/modules/ipfix/IpfixParser.cpp

And disambiguate log messages.

Correct indentation and braces so that it's readable

---

src/modules/ipfix/IpfixReceiverZmq.cpp

This allows calls set HWM socket options to happen on an unconnected
socket, thus working round ZMQ bug https://github.com/zeromq/libzmq/issues/2228
This works with both versions of ZMQ that do and do not have the bug.

split zsock_new_sub() into zsock_new() and zsock_connect()

---

configs/example.xml

Removes biflow aggregation from `example.xml` config file as it is not working at the moment.
Closes #53.

Fix default config file

---

src/modules/ipfix/IpfixReceiverZmq.cpp

Use idiomatic C++11: Modern for loop on a containers
Silences several cpp_check warnings
Minor debug logging around IpfixReceiverZmq zpoller

Idiomatic c++11

---

.travis.yml
src/modules/ipfix/database/IpfixDbWriterPg.cpp
src/modules/ipfix/database/IpfixDbWriterSQL.cpp

This pull requests makes Travis build the SQL Support modules by default to test whether it does work.

Travis compile db support

---

src/modules/analysis/HostStatistics.cpp

Invalid values in subnet configuration for HostStatistics result in crashes. Pull request improves the handling of the subnet configuration parameter.

Bugfix: Error out on invalid subnet in HostStatistics

---

.travis.yml
src/tests/vermonttest/CMakeLists.txt
src/tests/vermonttest/ConfigTester.cpp
src/tests/vermonttest/ConfigTester.h
src/tests/vermonttest/VermontTest.cpp

Out of source tree build

---

.travis.yml
src/modules/analysis/fpsigmatcher/Signature.c

and fix an off my one warning reported by gcc10

Add gcc9 and gcc10 to travis build

---

src/tests/ipfixlolib/CMakeLists.txt

Only enable the mtutest if UDP connect is enabled
