- src/modules/ipfix/CollectorCfg.h
Simplify equalTo list comparison thanks to
std vector comparison.
Sort vector in costructor so that equalTo will return True
if the content is the same, even if the order is scrambled,
since the entries order is not relevant.
At the moment, if the order of the strings in authorizedHosts is not the same, equalTo will return false. Since the order does not matter, sort the array in the costructor and then use the standard library vector comparison to compare them.
> Improve CollectorCfg::equalTo()

- src/modules/ipfix/IpfixRecord.cpp
- src/modules/ipfix/aggregator/Rule.cpp
If a template has a field that is not recognised by
IeInfo::getValidProtocols an exception will be thrown causing
Vermont to abort, even though there is an explicit exception
when the protocolId is part of the template.
Fix it by parsing all the fields first, and only then raise
an exception is no valid protocol is found.
Signed-off-by: Luca Boccassi <lboccass@brocade.com>
> Fix getValidProtocols exception if flow has protocolId

- src/core/InfoElementCfg.h
- src/modules/ipfix/Connection.cpp
- src/modules/ipfix/Connection.h
- src/modules/ipfix/IpfixCsExporter.cpp
- src/modules/ipfix/IpfixCsExporter.hpp
- src/modules/ipfix/IpfixNetflowExporter.cpp
- src/modules/ipfix/IpfixPayloadWriter.cpp
- src/modules/ipfix/IpfixSender.cpp
- src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
- src/modules/ipfix/aggregator/FlowHashtable.cpp
- src/modules/ipfix/aggregator/PacketHashtable.cpp
- src/modules/ipfix/aggregator/Rules.cpp
- src/modules/packet/Template.cpp
- Support 16 bits tcpControlFlags in the Ipfix Aggregator
The new Ipfix RFCs (7011 and 7012, see
http://www.iana.org/assignments/ipfix/ipfix.xhtml) have changed
the size of the tcpControlFlags from 1 byte to 2 bytes.
Some part of the code, like the ipfixlolib, already support it,
but the Ipfix Aggregator asserts when the field is not 1 byte long.
The RFC and IANA page specifically say that in case an exporter does
not support the upper flags, then 1 byte should be exported. So, in
Vermont, we have to support both cases in ingress. But internally, in
the aggregator, store everything in 2 bytes format. So if there is no
aggregator and an exporter sends 1 byte field, we export 1 byte. But
if there is an aggregator, convert to 2 bytes.
- Add option to disable auto add v4 mask
IPv4 address …
> Add support for 16 bits tcp flags (new RFC) and add option to disable autoadd of address mask

- src/core/ConnectionQueue.h
- src/core/InfoElementCfg.h
- src/core/Timer.h
- src/modules/analysis/P2PDetector.cpp
- src/modules/ipfix/CollectorCfg.h
- src/modules/ipfix/IpfixCollectorCfg.cpp
- src/modules/ipfix/IpfixCollectorCfg.h
- src/modules/ipfix/IpfixCsExporter.cpp
- src/modules/ipfix/IpfixExporterCfg.cpp
- src/modules/ipfix/IpfixNetflowExporter.cpp
- src/modules/ipfix/IpfixRecord.cpp
- src/modules/ipfix/IpfixRecord.hpp
- src/modules/ipfix/IpfixSender.cpp
- src/modules/ipfix/NetflowV9ConverterCfg.cpp
- src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
- src/modules/ipfix/aggregator/AggregatorBaseCfg.h
- src/modules/ipfix/aggregator/IpfixAggregatorCfg.cpp
- src/modules/ipfix/aggregator/Rule.cpp
- src/modules/ipfix/aggregator/Rule.hpp
- src/modules/ipfix/aggregator/Rules.cpp
- src/modules/ipfix/aggregator/Rules.hpp
- src/modules/packet/PSAMPExporterModule.cpp
When the configuration is reloaded, if a module config has not changed, they can be reused. This was not fully implemented, and these commits finish the work.
> Implement modules re-use on config reload

- CMakeLists.txt
- src/common/ipfixlolib/ipfixlolib.c
- src/common/ipfixlolib/ipfixlolib.h
- src/modules/ipfix/CollectorCfg.h
- src/modules/ipfix/IpfixExporterCfg.cpp
- src/modules/ipfix/IpfixFileWriter.cpp
- src/modules/ipfix/IpfixSender.cpp
- src/modules/ipfix/IpfixSender.hpp
- src/modules/packet/PSAMPExporterCfg.cpp
- src/modules/packet/PSAMPExporterModule.cpp
- src/modules/packet/PSAMPExporterModule.h
- src/tests/ipfixlolib/example_code.cc
- src/tests/ipfixlolib/example_code_2.c
- src/tests/ipfixlolib/mtutest.c
- src/tests/ipfixlolib/template_generation.c
- src/tests/ipfixlolib/test_everything.cc
The Linux kernel in the past couple of years has gained support for
Virtual Routing and Forwarding:
https://www.kernel.org/doc/Documentation/networking/vrf.txt
The SO_BINDTODEVICE socket option can be used to specify a particular
VRF other than the default.
Add support in ipfixlolib and in the configuration for the exporters.
A very common request from customers is to make it explicit in the logs when a message applies to a particular VRF, to disambiguate for example when IP addresses are mentioned (the same IP can be in different VRFs). So most of the diff is about adding this feature to the relevant logs.
> Support for exporting over a device (VRF)

- README.md
Just quick pass at reformatting the README into Markdown format so it's rendered better on Github.
Fixed and added a couple of links.
It could probably be tidied up further, removing some the out of dates sections on compiling with additional options.
> Markdown format for README

- src/modules/ipfix/IpfixParser.cpp
processNetflowV9Packet, processIpfixPacket: fixed the computation of the difference between the actual sequence number and the expected sequence number
> Fix the computation of the difference between the actual and the expected seq numbers

- CMakeLists.txt
CMake not only checks if the header exists, but tries to include and
compile it, which fails with linux/if.h since it needs another header
which it does not include itself.
Manually include it as a CFLAG in the CHECK_INCLUDE_FILE call to fix
it.
@ogasser noticed a small mistake in the previous PR - nothing bad as the include is only used to get a definition that is available as a fallback, but worth fixing anyway.
> Fix CMake check for linux/if.h

- .travis.yml
It's fine to include the package even when not used, as the compilation is explicitly controlled.
> Simplify the matrix of jobs, without having to explicitly use matrix

- src/core/Destination.h
- src/modules/analysis/FlowLenAnalyzer.cpp
- src/modules/analysis/FlowLenAnalyzer.h
Overloaded virtual functions were hidden because of different parameter lists.
Destination<NullEmitable*> implemented receive for Emitable* instead of NullEmitable*.
> fixed hiding of overloaded virtual functions

- src/core/Cfg.cpp
- src/core/Cfg.h
- src/modules/analysis/HostStatisticsCfg.cpp
Removed deprecated dynamic exception specification (IllegalEntry) from CfgBase::_get
> removed deprecated dynamic exception specification from Cfg

- CMakeLists.txt
The latest OLD behaviour of CMP0017 CMP0003 CMP0002 was changed after
2.8.4. No need to be as strict as 3.1
> More specific cmake version restriction

- .travis.yml
- src/modules/ipfix/IpfixExporterCfg.cpp
There was still some code that was unconditionally using dtls code,
which requires ssl. This has now been made conditional.
I suspect this is indicative of code smell here, and that perhaps
better encapsulation is needed around this. But that come later as
more attempts are made to modularise the code.
Fixes #85
> Fix building with SUPPORT_DTLS=OFF and libssl-dev not installed

- src/osdep/linux/sysinfo.cpp
After this clang will be building without warnings! :-)
Just need to get gcc building without warnings and we can finally enable -Werror in CMakeList.txt
> Remove unused variables

- src/modules/ipfix/IpfixPrinter.cpp
Exceptions are not to be thrown from destructors.
Normally I would have moved the closing of the file in a separate method, but calling it messes up the design (needs specialization of the CfgHelper template class). Instead, an error message is displayed -- aborting seems to drastic in this case.
> replaced the exception in the destructor with a msg

- configs/basiclist.xml
- src/common/ipfixlolib/ipfix_iana.c
- src/common/ipfixlolib/ipfix_iana.h
- src/common/ipfixlolib/ipfix_names.c
- src/common/ipfixlolib/ipfix_names.h
- src/core/InfoElementCfg.h
- src/modules/ipfix/IpfixPrinter.cpp
- src/modules/ipfix/IpfixPrinter.hpp
- src/modules/ipfix/IpfixRecord.hpp
- src/modules/ipfix/IpfixSender.cpp
- src/modules/ipfix/IpfixSender.hpp
- src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
- src/modules/ipfix/aggregator/BaseHashtable.cpp
- src/modules/ipfix/aggregator/PacketHashtable.cpp
- src/modules/ipfix/aggregator/PacketHashtable.h
- src/modules/ipfix/aggregator/Rule.hpp
- tools/iana_ipfix_parser/parse_iana_ipfix_elements.py
This adds the basicList IE to the exporter side. It allows to e.g. send a list of packet length of all packets within a flow. Due to the dynamic nature and variable length of basicList, significant changes to the codebase were necessary.
See RFC 6313 for more info on basicList.
@evintila and @nickbroon please thoroughly review :)
> Add basicList implementation

- dev/README
- dev/README.md
- dev/Vagrantfile
- dev/playbook.yml
- dev/roles/base/tasks/main.yml
Provides a vagrant setup where dependencies for vermont are automatically installed and vermont is build. 
After starting and provisioning the VM, vermont can be directly tested inside this VM.
> Add vagrant VM with automatic vermont setup

- src/modules/ipfix/aggregator/AggregatorBaseCfg.cpp
- src/modules/ipfix/aggregator/BaseHashtable.h
Add an error message when key/nonkey configuration doesn't match actual behaviour (as reported in #112).
Using a 'traditional' flow definition like that below will result in:
vermont[4729]: Field bgpDestinationAsNumber configured as nonFlowKey will not be Aggregated
vermont[4729]: Field bgpSourceAsNumber configured as nonFlowKey will not be Aggregated
vermont[4729]: Field destinationIPv4PrefixLength configured as nonFlowKey will not be Aggregated
vermont[4729]: Field egressInterface configured as nonFlowKey will not be Aggregated
vermont[4729]: Field ipNextHopIPv4Address configured as nonFlowKey will not be Aggregated
vermont[4729]: Field sourceIPv4PrefixLength configured as nonFlowKey will not be Aggregated
<rule>
<flowKey>
<ieName>destinationIPv4Address</ieName> …
> Error message when key/nonkey configuration doesn't match actual behaviour

- src/modules/ipfix/IpfixRecord.hpp
stringstream treats uint8_t as a char which in some cases may be
unprintable ascii (eg 255 might be the protocol), so explicitly print
it as a string so it can be read.
> Correct output the protocol as a string

- .travis.yml
- src/common/msg.h
Newer clang compilers all build just fine. gcc 8 fails to build, mainly in the XML code, that will need fixing.
scan-build example stage that shows static analysis errors that could be tackled.
Small code attributes to make the scan-build output less verbose.
> Additional compiler builds for Travis

- src/core/XMLNode.cpp
- src/modules/ConfigManager.cpp
Valgrind was reporting lots of leaks of the form:
```
==5048==    at 0x4C2BBAF: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5048==    by 0x5D50D18: xmlBufCreateSize (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==5048==    by 0x5CDDD91: xmlNodeGetContent (in /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.4)
==5048==    by 0x38EB01: XMLNode::getContent[abi:cxx11]() const (in /usr/sbin/vermont)
==5048==    by 0x285B62: CollectorCfg::CollectorCfg(XMLElement*, unsigned int) (in /usr/sbin/vermont)
```
The API guide for xmlNodeGetContent() states:
Returns: a new #xmlChar * or NULL if no content is available. It's up to the caller to free the memory with xmlFree().
So call xmlFree() after using the std:string copy constructor
Fixes #117
> Don't leak the xmlString in Cfg

- .gitmodules
Looks like @constcast constcast wiki repo has fallen off the internet :
fatal: remote error: access denied or repository not exported: /a/nw/ad/0c/93/1421452/254611723.wiki.git
fatal: clone of 'git://github.com/constcast/vermont.wiki.git' into submodule path '/Users/Nick/Software/vermont/docs/wiki' failed
Probably best to use tumi8 as that's the definitive uptream anyway.
> Use a wiki remote that exists

- src/modules/ipfix/aggregator/Rules.cpp
- src/modules/ipfix/aggregator/Rules.hpp
- src/tests/ipfixlolib/CMakeLists.txt
- src/tests/vermonttest/ConfigTester.cpp
- src/tests/vermonttest/ConfigTester.h
- src/tests/vermonttest/VermontTest.cpp
This pull requests addresses two issues and introduces another change:
- Build errors on clang10, which identifies a logic bug
- Invalid values for the match field for protocolIdentifier result in errors (fixes #134 )
- Runs vermonttest during travis builds
> Fix for parseProtoInformation

- src/modules/ipfix/database/IpfixDbWriterSQL.cpp
This PR adds default values for two variables, `ipfixId` and `enterpriseId`, in the `IpfixDbWriterSQL` class. Usually, these variables will always be set or an exception will be thrown, but gcc (tested with gcc 8.3.0 on debian) doesn't see this and will fail to compile due to `-Werror`. This commit fixes the issue by setting both variables to zero at initialization.
In case you need reproduction steps for the initial error:
- Use a fresh Debian 10 install and install all dependencies including libpg
- Execute `cmake -DSUPPORT_POSTGRESQL=True -DCMAKE_BUILD_TYPE=Release . && make`
This results in the following error:
```
[ 90%] Building CXX object src/modules/CMakeFiles/modules.dir/ipfix/database/IpfixDbWriterPg.cpp.o
/root/vermont-git/src/modules/ipfix/database/IpfixDbWriterSQL.cpp: In …
```
> Fixed compile error when using the IpfixDbWriter

- src/modules/analysis/TRWPortscanDetector.cpp
When TRWPortScanDetector is configured with  a too big hashbit size, it will result in a bad_alloc during allocation. This change provides explanatory error messages.
> TRWPortScanDetector: Provide better error messages on bad_alloc

- src/modules/ipfix/IpfixSamplerCfg.cpp
Too small or low values in the configuration of ipfixSampler can
lead to floating point exceptions during runtime.
> Bugfix: Wrong values for flowRate in ipfixSampler lead to crashes

- configs/simple.xml
- src/common/msg.cc
- src/common/msg.h
- src/modules/ConfigManager.cpp
- src/tests/vermonttest/ConfigTester.cpp
- src/vermont.cc
This allows the logging level to set as part of configuration, instead
of having to use the `-l` CLI option. This mean it can also be changed
dynamically when the config file is re-read for changes.
> Add a logging attribute to the ipfix config element

- src/modules/ipfix/Connection.cpp
Uninitialized values for srcTransOctets and dstTransOctets lead to
incorrectly printed values in table output of IpfixPrinter if no
transport octets are delivered in the flow
> Bugfix: Initialize transoctected in IpfixPrinter
